### ISSUE TITLE
ISOTP?

### ISSUE THREAD

**Issue by mickeyl** [mac-can/RusokuCAN.dylib#15]
Are there any plans to support automatic ISOTP segmentation on the controller layer for the TouCAN adapter?

Given the hardware specs, it looks like the controller could do this.

**Comment by mac-can** [comment]
It would be great to have a hardware implementation of the ISO/TP protocol (ISO 15765-2).

Can you pl. point me to the hardware specs.

**Comment by mickeyl** [comment]
Well, according to the fact sheet on the website, it‘s a Cortex M4 @100MHz and given the buffer of 20000 frames, isotp should be very possible.

**Comment by rusoku** [comment]
I don't have any ideas yet about command system between USB host and CAN device with implemented ISOTP protocol then.Currently TouCAN adapter is just dumb gate between CAN and USB buses.It sends can bus frames packed into usb frames only.
Can you point me to similar device existing in the market  with hardware implementaion of the ISOTP protocol?  For devices like PCAN and Kvaser all these protocols are implemented like external library.
I work on new dual CAN FD USB (ETH, WiFi) adapter based on STM32H7xx with external DDR 8MB memory and Zephyr RTOS and maybe is worth to add protocols like ISOTP, VSCP, OpenCAN, NMEA2000 etc... in this new adapter.

**Comment by mickeyl** [comment]
Well, ISOTP with its strong timing guarantees is always a struggle to do right in the higher layers, that's why almost all non-trivial (i.e. those which only work with OBD2 PIDs that are worth 2 bytes of data) adapters implement this on the controller.

The whole OBDLINK family, WGSoft.de UniCarScan, and almost all J2534 passthrough adapters do it.

**Comment by rusoku** [comment]
But adapters from manufacturers like Peak and Kvaser have implemented J2354 passthrough  protocol have like external dll library ? Not in the hardware ?
And yes they all use high speed USB 480 Mbit interface because full speed USB becomes too slow.
Maybe then is worth to develop  adapter for example based on STM32MP1xx mcu with Linux inside and to use SocketCAN...
In this case would be available a lot of interfaces like WiFI, EThernet, USB, Bluetooth...

I need to explore more ISOTP protocol because all my CAN bus toys are dedicated for VSCP home automation protocol.
