### ISSUE TITLE
pthread_mutex_init always returns non-negative values ?

### ISSUE THREAD

**Issue by rusoku** [mac-can/RusokuCAN.dylib#27]
in MacCAN_IOUsbKit.c  158 should be:
if(pthread_mutex_init(&usbDevice[index].ptMutex, NULL) > 0)
?

**Comment by mac-can** [comment]
Correct is `if (pthread_mutex_init(&usbDevice[index].ptMutex, NULL) != 0)`.

According to Mac OS X manual page (and also to POSIX specification) *if successful, `pthread_mutex_init()` will return zero ... .  Otherwise, an error number will be returned to indicate the error*.

The error number is not clearly defined, hence it could be a positive or a negative number.

-> Action: To be fixed.
