### ISSUE TITLE
MessageFilter?

### ISSUE THREAD

**Issue by mickeyl** [mac-can/RusokuCAN.dylib#9]
In `can_api.cpp:395` I see the witty comment

```c++
    // TODO: Hmm, what's about SetProperty? (Lucky me, there's nothing to be set)
```

Does that mean that the RusokuCAN adapter does not support message filter (masks) then?

**Comment by rusoku** [comment]
Hi,
TouCAN converter supports message filter.
Take a look at:  https://www.rusoku.com/storage/app/media/CANAL%20Library%20User%20Guide.pdf
CanalSetFilter11bit 
CanalSetFilter29bit

**Comment by mickeyl** [comment]
Thanks. Good to know that the hardware can do it. As far as I understand it though, it doesn't seem to be implemented in the USB driver https://github.com/mac-can/RusokuCAN/blob/52f784a4566fb9e4d4bfd2fa856cd29fa11fa2ce/Sources/TouCAN_Driver/TouCAN_USB.c:

```c
int TouCAN_set_filter_std_list_mask(CANUSB_Handle_t hDevice, Filter_Type_TypeDef type, UInt32 list, UInt32 mask) {
    return (int)TOUCAN_ERROR_OFFSET;
}

int TouCAN_set_filter_ext_list_mask(CANUSB_Handle_t hDevice, Filter_Type_TypeDef type, UInt32 list, UInt32 mask) {
    return (int)TOUCAN_ERROR_OFFSET;
}
```

Do you have a timeline for implementing this?

**Comment by mac-can** [comment]
Message filtering is currently not realized (in Software) for the TouCAN interface, neither for 11-bit identifiers nor for 29-bit identifiers.

It is correctly observed that is expected to be realized with setting filter code and filter mask by properties. But due to a not understood issue with a CAN interface based on an SJA1000 chip, the realization is postponed for now. I don´t want to run into later incompatibilities among the different CAN interfaces (e.g. PEAK-System or Kvaser).

**Comment by mickeyl** [comment]
Since over two years have passed without any message filters… did you abandon work on that?

**Comment by mac-can** [comment]
It is postponed since over ten years (I hate this messing around with binary masks for identifier filtering). But is is still on my agenda (maybe with the next major release).

**Comment by mickeyl** [comment]
Ok, let's cross fingers. I can't quite understand how you could get along without those filters for so long. since application-level filtering wastes so much power.

**Comment by mac-can** [comment]
[🎁](https://github.com/mac-can/RusokuCAN.dylib/releases/tag/v0.3)
